const items = [
  {
    "id": "g33kboy",
    "title": "Making a Game Boy Emulator – Let’s Play Tetris",
    "category": "Retro",
    "description": "Writing a Game Boy emulator is an absolute blast — until it suddenly isn’t.Tetris has a reputation for being “easy,” but it still threw me a few…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/wp-content/uploads/2025/11/image-1.png\" alt=\"Making a Game Boy Emulator – Let’s Play Tetris\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/game-boy-tetris/index.html",
    "featured": true,
    "date": "2025-11-18"
  },
  {
    "id": "zx-speculator-a-cross-platform-zx-spectrum-emulator",
    "title": "ZX Speculator: A Cross-Platform ZX Spectrum Emulator",
    "category": "Retro",
    "description": "Overview ZX Speculator is a robust, cross-platform ZX Spectrum 48K emulator developed in C#. It’s built using Avalonia for compatibility across…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/wp-content/uploads/2024/05/image-1.png\" alt=\"ZX Speculator: A Cross-Platform ZX Spectrum Emulator\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/zx-speculator-a-cross-platform-zx-spectrum-emulator/index.html",
    "featured": true,
    "date": "2024-05-15"
  },
  {
    "id": "xwing-360",
    "title": "Star Wars: X-Wing (360º)",
    "category": "Shaders",
    "description": "Following on from my previous post, I have used ShaderBoi to make a 360º YouTube video of my X-Wing shader. Enjoy! The GLSL shader source can be…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/youtube/0RnQJcFm1PM.jpg\" alt=\"Star Wars: X-Wing (360º)\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/xwing-360/index.html",
    "featured": false,
    "date": "2023-09-10"
  },
  {
    "id": "xwing",
    "title": "Star Wars: X-Wing from The Force Awakens",
    "category": "Shaders",
    "description": "When I first watched The Force Awakens I saw the scene where a group of X-Wings flew down a river, kicking up water spray behind them. And now…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/wp-content/uploads/2023/09/image-6.png\" alt=\"Star Wars: X-Wing from The Force Awakens\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/xwing/index.html",
    "featured": true,
    "date": "2023-09-09"
  },
  {
    "id": "butcanitruncrysis",
    "title": "But Can It Run Crysis?",
    "category": "Shaders",
    "description": "For years now I’ve loved the Crysis games, and so I’ve finally created a small tribute. The recently release ‘Remastered’ version introduced ray…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/youtube/rsIRB3Gxtwc.jpg\" alt=\"But Can It Run Crysis?\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/butcanitruncrysis/index.html",
    "featured": false,
    "date": "2023-08-21"
  },
  {
    "id": "dune-sand-worm-2-3-2-2-2-2",
    "title": "Revised Reality (Revision 2022 4Kb Graphics Demo)",
    "category": "Shaders",
    "description": "I’ve been watching graphics demos for many years now, and never thought that one day I’d actually make one myself. But this year I finally…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/wp-content/uploads/2022/05/RevisedReality-700x394.png\" alt=\"Revised Reality (Revision 2022 4Kb Graphics Demo)\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/dune-sand-worm-2-3-2-2-2-2/index.html",
    "featured": true,
    "date": "2022-04-18"
  },
  {
    "id": "dune-sand-worm-2-3-2-2-2",
    "title": "GLSL Shader Shrinker",
    "category": "Tools",
    "description": "I have been writing a tool over the last few months which will take GLSL shader code and optimize it in a variety of ways. It can apply a range…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/wp-content/uploads/2022/05/OneSmallStep-700x394.png\" alt=\"GLSL Shader Shrinker\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/dune-sand-worm-2-3-2-2-2/index.html",
    "featured": false,
    "date": "2022-04-10"
  },
  {
    "id": "dune-sand-worm-2-3-2-2",
    "title": "Aliens (Scanner scene)",
    "category": "Shaders",
    "description": "Another Aliens-themed shader, motivated by me watching this clip from the movie. I try to add add something new each time I make a shader, and…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/youtube/yimsQfjK8es.jpg\" alt=\"Aliens (Scanner scene)\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/dune-sand-worm-2-3-2-2/index.html",
    "featured": false,
    "date": "2022-03-01"
  },
  {
    "id": "dune-sand-worm-2-3-2",
    "title": "The Exorcist (1973)",
    "category": "Shaders",
    "description": "This is my first black and white shader, and also the first time I’ve mixed 2D and 3D content. As ever, in an attempt to keep the code small and…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/youtube/NseO7v3iylU.jpg\" alt=\"The Exorcist (1973)\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/dune-sand-worm-2-3-2/index.html",
    "featured": false,
    "date": "2022-01-04"
  },
  {
    "id": "dune-sand-worm-2-3",
    "title": "Innerspace (1989)",
    "category": "Shaders",
    "description": "I challenge anyone to not like the Innerspace movie! There’s a lot of new (to me) lighting effects in this shader. The headlights of the ‘pod’…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/youtube/TonMoR0KI_E.jpg\" alt=\"Innerspace (1989)\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/dune-sand-worm-2-3/index.html",
    "featured": false,
    "date": "2021-12-10"
  },
  {
    "id": "dune-sand-worm-2-2",
    "title": "The Alien",
    "category": "Shaders",
    "description": "Another shader based on Alien, this one was an exercise in modelling and animation. I started off with the dome of the head and the texture on…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/youtube/2QoR8L16Lc0.jpg\" alt=\"The Alien\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/dune-sand-worm-2-2/index.html",
    "featured": false,
    "date": "2021-10-24"
  },
  {
    "id": "dune-sand-worm-2",
    "title": "The Abyss (1989)",
    "category": "Shaders",
    "description": "Continuing the trend of making GLSL Shadertoy shaders from my favourite films, the next on my list was The Abyss (1989). I was stretching myself…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/youtube/SZqlIZMQU6U.jpg\" alt=\"The Abyss (1989)\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/dune-sand-worm-2/index.html",
    "featured": false,
    "date": "2021-09-11"
  },
  {
    "id": "dune-sand-worm",
    "title": "Dune (Sand Worm)",
    "category": "Shaders",
    "description": "There’s a new Dune movie coming out soon, so I thought I’d make a ‘Dune’ shader (based on the 1984 version). Nothing too complex in this scene.…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/youtube/GqkO68U4Hws.jpg\" alt=\"Dune (Sand Worm)\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/dune-sand-worm/index.html",
    "featured": false,
    "date": "2021-08-30"
  },
  {
    "id": "silence-of-the-lambs",
    "title": "Silence of the Lambs",
    "category": "Shaders",
    "description": "For this shader I wanted to write something that used textured stone walls, as I hadn’t really tried writing that effect before. The cell scene…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/youtube/DkaaJbfpNxE.jpg\" alt=\"Silence of the Lambs\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/silence-of-the-lambs/index.html",
    "featured": false,
    "date": "2021-08-24"
  },
  {
    "id": "the-fly",
    "title": "The Fly",
    "category": "Shaders",
    "description": "The challenge for this shader was to a) pay tribute to an awesome movie, and b) to add some animated content. I actually got quite attached to…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/youtube/Vq-9sCiXFLo.jpg\" alt=\"The Fly\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/the-fly/index.html",
    "featured": false,
    "date": "2021-08-01"
  },
  {
    "id": "ready-player-one",
    "title": "Ready Player One",
    "category": "Shaders",
    "description": "After watching Ready Player One way too many times (Then reading the book. Then reading the second book.), I figured I just had to write a…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/youtube/IbHhI6-2LX4.jpg\" alt=\"Ready Player One\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/ready-player-one/index.html",
    "featured": false,
    "date": "2021-07-16"
  },
  {
    "id": "glsl-shader-shrinker",
    "title": "GLSL Shader Shrinker",
    "category": "Tools",
    "description": "I have written many GLSL shaders over the last few years, most of which can be found on the Shadertoy website, and over time I’ve built up some…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/wp-content/uploads/2021/06/GLSLShaderShrinker.jpeg\" alt=\"GLSL Shader Shrinker\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/glsl-shader-shrinker/index.html",
    "featured": false,
    "date": "2021-06-08"
  },
  {
    "id": "3d-printing-prusa-mk3s",
    "title": "3D Printing – Prusa Mk3s",
    "category": "Hardware",
    "description": "After several months of deliberation and research, I finally decided to take the plunge into the world of 3D printing. As a professional…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/wp-content/uploads/2020/03/Lack-enclosure.jpg\" alt=\"3D Printing – Prusa Mk3s\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/3d-printing-prusa-mk3s/index.html",
    "featured": false,
    "date": "2019-09-01"
  },
  {
    "id": "self-balancing-robot",
    "title": "Self-balancing Robot",
    "category": "Hardware",
    "description": "So I decided to practise some of my recently-acquired Arduino skillz to try and make a self-balancing robot. The idea of a robot managing to…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/wp-content/uploads/2020/03/Balancing-Robot-Assembled-scaled.jpg\" alt=\"Self-balancing Robot\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/self-balancing-robot/index.html",
    "featured": true,
    "date": "2019-06-01"
  },
  {
    "id": "arduino-code-performance",
    "title": "Arduino Code – Performance",
    "category": "Hardware",
    "description": "I’m currently making a self balancing robot, powered by an Arduino Nano, and decided to use NEMA 17 stepper motors to power it. The DRV8825…",
    "art": "archive-art",
    "visual": "<span class=\"text-preview\">Hardware<b>Arduino Code – Performance</b></span>",
    "url": "articles/arduino-code-performance/index.html",
    "featured": false,
    "date": "2019-04-09"
  },
  {
    "id": "arduino-code-timed-events",
    "title": "Arduino Code – Timed Events",
    "category": "Hardware",
    "description": "In most of my Arduino projects I find myself in a situation where two things apply: My void loop() function needs to run very quickly. I need to…",
    "art": "archive-art",
    "visual": "<span class=\"text-preview\">Hardware<b>Arduino Code – Timed Events</b></span>",
    "url": "articles/arduino-code-timed-events/index.html",
    "featured": false,
    "date": "2019-04-07"
  },
  {
    "id": "complementary-filter",
    "title": "Arduino Code – Complementary Filter",
    "category": "Hardware",
    "description": "My current Arduino project is a self-balancing robot, which requires repeatedly reading angle and acceleration values from an MPU-6050 gyro.…",
    "art": "archive-art",
    "visual": "<span class=\"text-preview\">Hardware<b>Arduino Code – Complementary Filter</b></span>",
    "url": "articles/complementary-filter/index.html",
    "featured": false,
    "date": "2019-04-02"
  },
  {
    "id": "arduino-code-logging",
    "title": "Arduino Code – Logging",
    "category": "Hardware",
    "description": "Needing to write output to the Arduino IDE’s ‘Serial Monitor’ is something you might find yourself doing a lot. It’s one of the easiest ways of…",
    "art": "archive-art",
    "visual": "<span class=\"text-preview\">Hardware<b>Arduino Code – Logging</b></span>",
    "url": "articles/arduino-code-logging/index.html",
    "featured": false,
    "date": "2019-03-07"
  },
  {
    "id": "arduino-coding-custom-code",
    "title": "Arduino Code – Header Files",
    "category": "Hardware",
    "description": "Code Bloat I have been coding for the Arduino for a while now, and over time I have written a small collection of routines that can be reused in…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/wp-content/uploads/2019/04/Screen-Shot-2019-04-07-at-15.23.33.png\" alt=\"Arduino Code – Header Files\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/arduino-coding-custom-code/index.html",
    "featured": false,
    "date": "2019-02-07"
  },
  {
    "id": "useless-box-the-code",
    "title": "Useless Box – The Code",
    "category": "Hardware",
    "description": "The Code For anyone planning on making their own ‘Useless Box’, you might find my Arduino Sketch(/code) useful as a starting point.  The version…",
    "art": "archive-art",
    "visual": "<span class=\"text-preview\">Hardware<b>Useless Box – The Code</b></span>",
    "url": "articles/useless-box-the-code/index.html",
    "featured": false,
    "date": "2018-09-01"
  },
  {
    "id": "useless-box",
    "title": "Useless Box – Final Result",
    "category": "Hardware",
    "description": "Here it is – The final result! Powered using an Arduino Uno, two ‘reclaimed’ servos, and a handful of Lego blocks.  Great fun to make, a good…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/youtube/320A49vx9M0.jpg\" alt=\"Useless Box – Final Result\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/useless-box/index.html",
    "featured": true,
    "date": "2018-08-31"
  },
  {
    "id": "useless-box-nearly-finished",
    "title": "Useless Box – Nearly Finished!",
    "category": "Hardware",
    "description": "Getting Close Another evening of ‘I Made A Thing’-ing, and I’m happy with the results. I’ve used a ‘ProtoShield‘ to help tidy up the wiring. …",
    "art": "archive-art",
    "visual": "<span class=\"text-preview\">Hardware<b>Useless Box – Nearly Finished!</b></span>",
    "url": "articles/useless-box-nearly-finished/index.html",
    "featured": false,
    "date": "2018-08-28"
  },
  {
    "id": "useless-box-arduino",
    "title": "Useless Box – Arduino",
    "category": "Hardware",
    "description": "First Arduino/Servo test I’ve popped the lid back on to the top of the box and used my breakout board as a ‘go between’ from the servos and…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/wp-content/uploads/2018/10/Useless-Box-Breadboard-Arduino.jpg\" alt=\"Useless Box – Arduino\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/useless-box-arduino/index.html",
    "featured": false,
    "date": "2018-08-24"
  },
  {
    "id": "useless-box-the-finger-pt-2",
    "title": "Useless Box – The Finger (Pt 2)",
    "category": "Hardware",
    "description": "Quick Update I’ve been looking for a better ‘finger’ for my useless box.  A Halloween-style finger would be great, but trying to find one of a…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/wp-content/uploads/2018/10/Useless-Box-Nerf-bullet.jpg\" alt=\"Useless Box – The Finger (Pt 2)\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/useless-box-the-finger-pt-2/index.html",
    "featured": false,
    "date": "2018-08-23"
  },
  {
    "id": "useless-box-the-finger",
    "title": "Useless Box – The Finger (Pt 1)",
    "category": "Hardware",
    "description": "The Finger So I’ve got a rudimentary ‘box’ built, and I know how to control the servos with an Arduino. I figured the next step is to work on…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/wp-content/uploads/2018/10/Photo-20-08-2018-20-37-15.jpg\" alt=\"Useless Box – The Finger (Pt 1)\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/useless-box-the-finger/index.html",
    "featured": false,
    "date": "2018-08-22"
  },
  {
    "id": "useless-box-lego-time",
    "title": "Useless Box – Lego Time",
    "category": "Hardware",
    "description": "Designing The Box When it came to the box I was in two minds – Either I make it in wood, or Lego.  (Give me a few months and ‘plastic’ would be…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/wp-content/uploads/2018/08/Useless-Box-Box.jpg\" alt=\"Useless Box – Lego Time\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/useless-box-lego-time/index.html",
    "featured": false,
    "date": "2018-08-19"
  },
  {
    "id": "useless-box-the-servos",
    "title": "Useless Box – The Servos",
    "category": "Hardware",
    "description": "Servos Getting a servo to move is a bit more complicated that getting an electric motor to spin, but not much so. Servos are typically limited…",
    "art": "archive-art",
    "visual": "<img src=\"assets/archive/wp-content/uploads/2018/08/Photo-18-08-2018-14-57-02-e1538684212902-700x525.jpg\" alt=\"Useless Box – The Servos\" loading=\"lazy\" draggable=\"false\">",
    "url": "articles/useless-box-the-servos/index.html",
    "featured": false,
    "date": "2018-08-18"
  },
  {
    "id": "useless-box-the-beginning",
    "title": "Useless Box – The Beginning",
    "category": "Hardware",
    "description": "The Beginning So this is it – My first Arduino project!  After months of see YouTube videos and Twitter updates from people working on their own…",
    "art": "archive-art",
    "visual": "<span class=\"text-preview\">Hardware<b>Useless Box – The Beginning</b></span>",
    "url": "articles/useless-box-the-beginning/index.html",
    "featured": false,
    "date": "2018-08-17"
  },
  {
    "id": "sample-page",
    "title": "About",
    "category": "About",
    "description": "A professional Software Developer with over 20 years of experience. Likes making things. Things like these…",
    "art": "archive-art",
    "visual": "<span class=\"text-preview\">About<b>About</b></span>",
    "url": "articles/sample-page/index.html",
    "featured": false,
    "date": "2018-10-02"
  }
];
